export const FETCH_TEAM_RANKINGS = 'fetch_team_rankings'
export const FETCH_TEAM_ROSTER = 'fetch_team_roster'
export const SET_CONFERENCE_FILTER = 'set_conference_filter'
export const SET_TEAM_FILTER = 'set_team_filter'
export const SET_PLAYER_FILTER = 'set_player_filter'